version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: en-ruta-db
    environment:
      POSTGRES_DB: enruta_db
      POSTGRES_USER: enruta
      POSTGRES_PASSWORD: enruta123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - en-ruta-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enruta"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Aplicación NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: en-ruta-api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://enruta:enruta123@postgres:5432/enruta_db?schema=public
      DIRECT_URL: postgresql://enruta:enruta123@postgres:5432/enruta_db?schema=public
      JWT_SECRET: secret
      JWT_EXPIRATION: 360d
      PORT: 3000
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_SECURE: false
      EMAIL_USER: pjimenez2510@gmail.com
      EMAIL_PASSWORD: vbxj ddvn vnss qobl
      EMAIL_FROM_NAME: EnRuta - Sistema de Transporte
      EMAIL_FROM_ADDRESS: pjimenez2510@gmail.com
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - en-ruta-network
    restart: unless-stopped
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        node dist/src/main.js
      "

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: en-ruta-redis
    ports:
      - "6379:6379"
    networks:
      - en-ruta-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  en-ruta-network:
    driver: bridge 