services:
  - type: web
    name: en-ruta-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: en-ruta-db
          property: connectionString
      # Variables de email - configurar en el dashboard de Render
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
      # Estas deben configurarse como secretos en Render
      # - key: EMAIL_USER
      #   value: tu-email@gmail.com
      # - key: EMAIL_PASSWORD
      #   value: tu-app-password
      - key: EMAIL_FROM_NAME
        value: EnRuta - Sistema de Transporte
      # JWT Secret - configurar como secreto en Render
      # - key: JWT_SECRET
      #   value: tu-jwt-secret-muy-seguro

databases:
  - name: en-ruta-db
    databaseName: enruta_db
    user: enruta_user
    plan: free 