export enum TipoUsuario {
  CLIENTE = 'CLIENTE',
  ADMIN_SISTEMA = 'ADMIN_SISTEMA',
  PERSONAL_COOPERATIVA = 'PERSONAL_COOPERATIVA',
}

export enum RolUsuario {
  ADMIN_COOPERATIVA = 'ADMIN_COOPERATIVA',
  OFICINISTA = 'OFICINISTA',
  CONDUCTOR = 'CONDUCTOR',
  AYUDANTE = 'AYUDANTE',
}
